@extends('index')

@section('pageTitle', 'Eunbyeol Shin')

@section('css')
@endsection

@section('js')

@endsection

@section('content')
    <div id="like_button_container">
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
        인트로<br>
    </div>
@endsection 